import {
  Device,
  Sensor,
  Incident,
  MaintenanceRecord,
  LocationItem,
  NotificationItem,
  AuditLogItem,
  SystemSettings,
  SensorType,
} from '../types';

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'loc-kigali-hq',
    name: 'Kigali Head Office',
    organizationId: 'org-rwanda-demo',
    address: 'KN 3 Ave, Downtown CBD',
    city: 'Kigali',
    district: 'Nyarugenge',
    province: 'Kigali City',
    country: 'Rwanda',
    buildingType: 'Office',
    contactPerson: 'Jean-Paul Mugisha (Facilities Director)',
    contactPhone: '+250 788 123 456',
    deviceCount: 2,
    activeAlertsCount: 0,
  },
  {
    id: 'loc-masaka-warehouse',
    name: 'Masaka Logistics & Storage Hub',
    organizationId: 'org-rwanda-demo',
    address: 'Masaka Industrial Zone, RN3 Highway',
    city: 'Kigali',
    district: 'Kicukiro',
    province: 'Kigali City',
    country: 'Rwanda',
    buildingType: 'Warehouse',
    contactPerson: 'Aline Umutoni (Logistics Operations)',
    contactPhone: '+250 788 234 567',
    deviceCount: 1,
    activeAlertsCount: 0,
  },
  {
    id: 'loc-green-hills',
    name: 'Green Hills Academy Campus',
    organizationId: 'org-rwanda-demo',
    address: 'KG 278 St, Nyarutarama',
    city: 'Kigali',
    district: 'Gasabo',
    province: 'Kigali City',
    country: 'Rwanda',
    buildingType: 'School',
    contactPerson: 'David Kwizera (Campus Safety Lead)',
    contactPhone: '+250 788 345 678',
    deviceCount: 1,
    activeAlertsCount: 0,
  },
  {
    id: 'loc-musanze-lodge',
    name: 'Musanze Mountain Eco-Lodge',
    organizationId: 'org-rwanda-demo',
    address: 'Kinigi Foothills Road, Volcanoes Zone',
    city: 'Musanze',
    district: 'Musanze',
    province: 'Northern Province',
    country: 'Rwanda',
    buildingType: 'Hotel',
    contactPerson: 'Grace Uwase (General Manager)',
    contactPhone: '+250 788 456 789',
    deviceCount: 1,
    activeAlertsCount: 0,
  },
];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev-cra-001',
    deviceCode: 'CRA-001',
    name: 'Kigali HQ - Server Room & Operations Hub',
    locationId: 'loc-kigali-hq',
    locationName: 'Kigali Head Office',
    organizationId: 'org-rwanda-demo',
    status: 'online',
    connectionType: '4G',
    batteryLevel: 94,
    firmwareVersion: 'v2.4.1',
    ipAddress: '10.12.4.15',
    macAddress: '3C:71:BF:12:0A:91',
    assignedTechnicianId: 'tech-01',
    assignedTechnicianName: 'Emmanuel Nshimiyimana',
    lastSeen: new Date().toISOString(),
    createdAt: '2026-01-15T08:00:00Z',
    sensorsCount: 12,
  },
  {
    id: 'dev-cra-002',
    deviceCode: 'CRA-002',
    name: 'Masaka Warehouse - Bay A Chemical & Dry Storage',
    locationId: 'loc-masaka-warehouse',
    locationName: 'Masaka Logistics & Storage Hub',
    organizationId: 'org-rwanda-demo',
    status: 'online',
    connectionType: '4G',
    batteryLevel: 87,
    firmwareVersion: 'v2.4.1',
    ipAddress: '10.12.8.22',
    macAddress: '3C:71:BF:33:4B:10',
    assignedTechnicianId: 'tech-01',
    assignedTechnicianName: 'Emmanuel Nshimiyimana',
    lastSeen: new Date().toISOString(),
    createdAt: '2026-02-01T09:30:00Z',
    sensorsCount: 12,
  },
  {
    id: 'dev-cra-003',
    deviceCode: 'CRA-003',
    name: 'Green Hills - Science Laboratories & STEM Block',
    locationId: 'loc-green-hills',
    locationName: 'Green Hills Academy Campus',
    organizationId: 'org-rwanda-demo',
    status: 'online',
    connectionType: 'WiFi',
    batteryLevel: 98,
    firmwareVersion: 'v2.4.0',
    ipAddress: '192.168.10.45',
    macAddress: '48:E7:29:8C:77:21',
    assignedTechnicianId: 'tech-02',
    assignedTechnicianName: 'Patrick Habimana',
    lastSeen: new Date().toISOString(),
    createdAt: '2026-02-14T11:00:00Z',
    sensorsCount: 12,
  },
  {
    id: 'dev-cra-004',
    deviceCode: 'CRA-004',
    name: 'Musanze Eco-Lodge - Commercial Kitchen & Fuel Vault',
    locationId: 'loc-musanze-lodge',
    locationName: 'Musanze Mountain Eco-Lodge',
    organizationId: 'org-rwanda-demo',
    status: 'online',
    connectionType: '4G',
    batteryLevel: 79,
    firmwareVersion: 'v2.4.1',
    ipAddress: '10.15.2.10',
    macAddress: '3C:71:BF:90:5E:8A',
    assignedTechnicianId: 'tech-02',
    assignedTechnicianName: 'Patrick Habimana',
    lastSeen: new Date().toISOString(),
    createdAt: '2026-03-01T14:15:00Z',
    sensorsCount: 12,
  },
];

export function generateSensorsForDevice(device: Device): Sensor[] {
  const baseTime = new Date().toISOString();
  return [
    {
      id: `sns-${device.deviceCode}-fire`,
      sensorCode: `${device.deviceCode}-FIR`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'FIRE',
      measurement: 'Flame / Optical IR',
      unit: 'Flame (0/1)',
      status: 'NORMAL',
      lastReading: 0,
      warningThreshold: 0.5,
      criticalThreshold: 1.0,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '0 (No Flame Detected)',
      description: 'Dual-band Infrared optical flame sensor for instantaneous ignition tracking.',
    },
    {
      id: `sns-${device.deviceCode}-smoke`,
      sensorCode: `${device.deviceCode}-SMK`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'SMOKE',
      measurement: 'Smoke Density / Optical Chamber',
      unit: '% obs/m',
      status: 'NORMAL',
      lastReading: 0.8,
      warningThreshold: 2.5,
      criticalThreshold: 5.0,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '< 2.0 % obs/m',
      description: 'Photoelectric smoke obscuration chamber calibrated to EN 54-7 guidelines.',
    },
    {
      id: `sns-${device.deviceCode}-temp`,
      sensorCode: `${device.deviceCode}-TMP`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'TEMPERATURE',
      measurement: 'Ambient Temperature',
      unit: '°C',
      status: 'NORMAL',
      lastReading: 22.4,
      warningThreshold: 45.0,
      criticalThreshold: 60.0,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '18°C – 32°C',
      description: 'High-precision digital thermopile sensor (±0.2°C tolerance).',
    },
    {
      id: `sns-${device.deviceCode}-gas`,
      sensorCode: `${device.deviceCode}-GAS`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'GAS',
      measurement: 'Combustible & Toxic Gas (LPG/Methane/CO)',
      unit: 'ppm',
      status: 'NORMAL',
      lastReading: 12,
      warningThreshold: 80,
      criticalThreshold: 200,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '< 50 ppm',
      description: 'Electrochemical & MOX catalytic bead sensor for hydrocarbon & carbon monoxide vapors.',
    },
    {
      id: `sns-${device.deviceCode}-water`,
      sensorCode: `${device.deviceCode}-WTR`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'WATER',
      measurement: 'Sub-floor Water Ingress / Leak Probe',
      unit: 'Wet (0/1)',
      status: 'NORMAL',
      lastReading: 0,
      warningThreshold: 0.5,
      criticalThreshold: 1.0,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '0 (Dry Contact)',
      description: 'Gold-plated conductive trace boundary sensing cable & spot probe.',
    },
    {
      id: `sns-${device.deviceCode}-door`,
      sensorCode: `${device.deviceCode}-DOR`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'DOOR',
      measurement: 'Magnetic Access Latch Status',
      unit: 'Open (0/1)',
      status: 'NORMAL',
      lastReading: 0,
      warningThreshold: 0.5,
      criticalThreshold: 1.0,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '0 (Firmly Closed & Latched)',
      description: 'Hall-effect magnetic reed switch monitoring physical barrier closure.',
    },
    {
      id: `sns-${device.deviceCode}-motion`,
      sensorCode: `${device.deviceCode}-MOT`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'MOTION',
      measurement: 'Passive Infrared (PIR) Motion Detection',
      unit: 'Activity (0/1)',
      status: 'NORMAL',
      lastReading: 0,
      warningThreshold: 0.5,
      criticalThreshold: 1.0,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '0 (No Intrusion Detected)',
      description: 'Wide-angle Fresnel quad-element PIR motion detection sensor.',
    },
    {
      id: `sns-${device.deviceCode}-sound`,
      sensorCode: `${device.deviceCode}-SND`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'SOUND',
      measurement: 'Acoustic Sound Pressure / Glass Breakage',
      unit: 'dB(A)',
      status: 'NORMAL',
      lastReading: 46,
      warningThreshold: 85,
      criticalThreshold: 105,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '35 – 65 dB(A)',
      description: 'MEMS microphone with fast peak detection for sudden impact or shatter frequencies.',
    },
    {
      id: `sns-${device.deviceCode}-humidity`,
      sensorCode: `${device.deviceCode}-HUM`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'HUMIDITY',
      measurement: 'Relative Humidity',
      unit: '% RH',
      status: 'NORMAL',
      lastReading: 54,
      warningThreshold: 80,
      criticalThreshold: 92,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '40% – 65% RH',
      description: 'Capacitive polymer hygrometer measuring airborne vapor saturation.',
    },
    {
      id: `sns-${device.deviceCode}-airq`,
      sensorCode: `${device.deviceCode}-AQI`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'AIR_QUALITY',
      measurement: 'Air Quality Index (PM2.5 / VOC)',
      unit: 'AQI',
      status: 'NORMAL',
      lastReading: 32,
      warningThreshold: 100,
      criticalThreshold: 200,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '< 50 AQI (Good)',
      description: 'Laser particulate scattering monitor detecting PM2.5 and PM10 particles.',
    },
    {
      id: `sns-${device.deviceCode}-battery`,
      sensorCode: `${device.deviceCode}-BAT`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'BATTERY',
      measurement: 'Internal LiPo Backup Battery',
      unit: '%',
      status: 'NORMAL',
      lastReading: device.batteryLevel,
      warningThreshold: 25,
      criticalThreshold: 15,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '60% – 100%',
      description: 'Fuel-gauge voltage and coulomb counter with uninterruptible power fallback.',
    },
    {
      id: `sns-${device.deviceCode}-conn`,
      sensorCode: `${device.deviceCode}-NET`,
      deviceId: device.id,
      deviceCode: device.deviceCode,
      locationId: device.locationId,
      locationName: device.locationName,
      sensorType: 'CONNECTIVITY',
      measurement: 'Cellular 4G / Wi-Fi Signal Link Quality',
      unit: 'CSQ',
      status: 'NORMAL',
      lastReading: 26,
      warningThreshold: 12,
      criticalThreshold: 6,
      lastUpdated: baseTime,
      calibrationStatus: 'CALIBRATED',
      normalRangeText: '18 – 31 CSQ (Strong)',
      description: 'Carrier link quality monitor tracking RSSI and packet latency.',
    },
  ];
}

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-2026-0921-01',
    incidentCode: 'INC-260921-01',
    deviceId: 'dev-cra-004',
    deviceCode: 'CRA-004',
    locationId: 'loc-musanze-lodge',
    locationName: 'Musanze Mountain Eco-Lodge',
    organizationId: 'org-rwanda-demo',
    eventType: 'Possible Gas Leak / Air Toxicity Alert',
    severity: 'WARNING',
    status: 'RESOLVED',
    triggeredSensors: ['GAS'],
    sensorReadings: [
      { sensorType: 'GAS', value: 115, unit: 'ppm', threshold: 80 },
    ],
    aiAnalysis: {
      eventType: 'Possible Gas Leak / Air Toxicity Alert',
      severity: 'WARNING',
      confidence: 0.84,
      sensorsInvolved: ['GAS'],
      explanation:
        'LPG kitchen line connection valve showed pressure drop and localized volatile vapor elevation. No open flame or thermal anomaly was detected.',
      recommendedAction:
        'Isolate commercial stove regulator valve and inspect brass fittings with soapy water solution.',
      timestamp: '2026-09-21T18:42:00Z',
      modelUsed: 'ClearRescue-RuleEngine-v2',
    },
    createdTime: '2026-09-21T18:42:15Z',
    acknowledgedTime: '2026-09-21T18:45:10Z',
    acknowledgedBy: 'Grace Uwase',
    resolvedTime: '2026-09-21T19:30:00Z',
    resolvedBy: 'Patrick Habimana (Technician)',
    assignedTechnician: 'Patrick Habimana',
    notes: [
      'Line valve 3 replaced and tested under 3.5 bar nitrogen pressure.',
      'Sensor reading returned to nominal 14 ppm baseline.',
    ],
    disclaimer:
      'Emergency-monitoring prototype platform. Does not replace certified gas detection or official safety apparatus.',
  },
  {
    id: 'inc-2026-0925-02',
    incidentCode: 'INC-260925-02',
    deviceId: 'dev-cra-002',
    deviceCode: 'CRA-002',
    locationId: 'loc-masaka-warehouse',
    locationName: 'Masaka Logistics & Storage Hub',
    organizationId: 'org-rwanda-demo',
    eventType: 'Possible Water Leak or Flooding',
    severity: 'WARNING',
    status: 'RESOLVED',
    triggeredSensors: ['WATER', 'HUMIDITY'],
    sensorReadings: [
      { sensorType: 'WATER', value: 1, unit: 'Wet (0/1)', threshold: 0.5 },
      { sensorType: 'HUMIDITY', value: 84, unit: '% RH', threshold: 80 },
    ],
    aiAnalysis: {
      eventType: 'Possible Water Leak or Flooding',
      severity: 'WARNING',
      confidence: 0.89,
      sensorsInvolved: ['WATER', 'HUMIDITY'],
      explanation:
        'Water detection probe activated at eastern wall conduit alongside a 28% jump in localized relative humidity.',
      recommendedAction:
        'Check roof drainage downspouts and exterior storm water channel for blockage.',
      timestamp: '2026-09-25T03:15:00Z',
      modelUsed: 'ClearRescue-RuleEngine-v2',
    },
    createdTime: '2026-09-25T03:15:20Z',
    acknowledgedTime: '2026-09-25T03:22:00Z',
    acknowledgedBy: 'Aline Umutoni',
    resolvedTime: '2026-09-25T05:00:00Z',
    resolvedBy: 'Emmanuel Nshimiyimana',
    assignedTechnician: 'Emmanuel Nshimiyimana',
    notes: ['Exterior roof gutter cleared after heavy tropical downpour. Water dried completely.'],
    disclaimer:
      'Emergency-monitoring prototype platform. Does not replace certified water alarms or flood telemetry systems.',
  },
];

export const INITIAL_MAINTENANCE: MaintenanceRecord[] = [
  {
    id: 'maint-2026-101',
    ticketCode: 'MNT-00101',
    deviceId: 'dev-cra-001',
    deviceCode: 'CRA-001',
    locationName: 'Kigali Head Office',
    technicianId: 'tech-01',
    technicianName: 'Emmanuel Nshimiyimana',
    title: 'Quarterly Sensor Calibration & LiPo Battery Test',
    description: 'Perform optical chamber aerosol calibration and battery capacity discharge cycle test.',
    priority: 'MEDIUM',
    status: 'COMPLETED',
    partsReplaced: 'None (Calibration Passed)',
    scheduledDate: '2026-09-10T09:00:00Z',
    completedDate: '2026-09-10T11:30:00Z',
    notes: 'All 12 sensor channels validated against calibrated reference meters. Signal CSQ measured 27/31.',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'maint-2026-102',
    ticketCode: 'MNT-00102',
    deviceId: 'dev-cra-004',
    deviceCode: 'CRA-004',
    locationName: 'Musanze Mountain Eco-Lodge',
    technicianId: 'tech-02',
    technicianName: 'Patrick Habimana',
    title: 'Post-Gas Incident Sensor Verification & Antenna Alignment',
    description: 'Inspect gas sensing chamber after kitchen incident and mount directional high-gain 4G antenna.',
    priority: 'HIGH',
    status: 'COMPLETED',
    partsReplaced: 'MOX Gas Sensor Probe & 4G Whip Antenna',
    scheduledDate: '2026-09-22T10:00:00Z',
    completedDate: '2026-09-22T13:45:00Z',
    notes: 'Installed replacement sensor module SN #CRA-PROBE-449. Verified zero-drift telemetry on dashboard.',
    createdAt: '2026-09-21T19:00:00Z',
  },
  {
    id: 'maint-2026-103',
    ticketCode: 'MNT-00103',
    deviceId: 'dev-cra-003',
    deviceCode: 'CRA-003',
    locationName: 'Green Hills Academy Campus',
    technicianId: 'tech-02',
    technicianName: 'Patrick Habimana',
    title: 'Firmware Upgrade to v2.4.1 & Wi-Fi Mesh Re-binding',
    description: 'Update microcontroller OTA image to latest v2.4.1 security release and test fallback 4G module.',
    priority: 'LOW',
    status: 'SCHEDULED',
    partsReplaced: 'Pending',
    scheduledDate: '2026-09-30T14:00:00Z',
    notes: 'Coordinated with school IT department during afternoon sports recess.',
    createdAt: '2026-09-26T10:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-001',
    title: 'Clear Rescue AI Operational Status: Nominal',
    message: 'All 4 monitoring units across Kigali, Masaka, and Musanze are reporting live telemetry with 0 critical alarms.',
    severity: 'INFO',
    channel: 'IN_APP',
    isRead: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-002',
    title: 'System Firmware v2.4.1 Available',
    message: 'Firmware update v2.4.1 ready for deployment with enhanced ESP32 deep-sleep power savings and MQTT TLS 1.3 support.',
    severity: 'INFO',
    channel: 'IN_APP',
    isRead: true,
    createdAt: '2026-09-26T08:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'audit-001',
    userId: 'user-admin-01',
    userEmail: 'ishimweclement537@gmail.com',
    action: 'SYSTEM_BOOT',
    resource: 'Platform Engine',
    details: 'Clear Rescue AI engine initialized with Firebase Firestore persistence and AI telemetry pipeline.',
    ipAddress: '197.243.10.4',
    timestamp: '2026-09-27T08:00:00Z',
  },
  {
    id: 'audit-002',
    userId: 'user-admin-01',
    userEmail: 'ishimweclement537@gmail.com',
    action: 'DEVICE_ONLINE',
    resource: 'dev-cra-001',
    details: 'Hardware unit CRA-001 registered heartbeat via 4G cellular bridge from Kigali HQ.',
    ipAddress: '10.12.4.15',
    timestamp: '2026-09-27T08:01:00Z',
  },
  {
    id: 'audit-003',
    userId: 'user-tech-01',
    userEmail: 'emmanuel.tech@clearrescue.rw',
    action: 'CALIBRATION_LOG',
    resource: 'sns-CRA-001-temp',
    details: 'Verified thermopile calibration against laboratory benchmark probe.',
    ipAddress: '197.243.22.18',
    timestamp: '2026-09-27T10:15:00Z',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  smsGatewayEnabled: false, // Development placeholder
  emailAlertsEnabled: false, // Development placeholder
  pushNotificationsEnabled: true,
  aiAnalysisSensitivity: 'BALANCED',
  emergencyCallAutomationPlaceholder: false,
  rwandaEmergencyNumber: '111 (Fire) / 112 (Police) / 912 (SAMU Ambulance)',
  soundAlertEnabled: true,
  simulationModeActive: true,
  dataRetentionDays: 90,
};
